name = "update-bell-app"
compatibility_date = "2025-11-30"
pages_build_output_dir = "dist"

compatibility_flags = ["nodejs_compat"]

[vars]
VITE_VAPID_PUBLIC_KEY = "BH282dXgVsQ2OA9j6guwx0emhXDg2mjtiePsGduQ5r6hD1VcThcxtBAuL2P3dXUUNzObwGsl0i9qG5smXe11c7M"

[[kv_namespaces]]
binding = "REMINDER_STORE"
id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" # ここは変更しないでください
